name: 'Composite Action'
description: 'Swethas First Test'
author: 'Swetha Hedlund'

# Define your inputs here.
inputs:
  who-to-greet:
    description: 'Your input description here'
    required: true
    default: 'World'

# Define your outputs here.
outputs:
  greeting:
    description: 'Your output description here'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
